<?php

declare(strict_types=1);

use SlevomatCodingStandard\Sniffs\Classes\ForbiddenPublicPropertySniff;
use SlevomatCodingStandard\Sniffs\TypeHints\ReturnTypeHintSniff;
use StanislasPoisson\DevTools\Insights;

return Insights::config([
    'exclude' => [
        'data',
        // Generated by the Symfony test kernel and ignored by Git: it is not part of the package.
        'config/reference.php',
        'schemas',
    ],

    'config' => [
        // Eloquent declares $incrementing and $timestamps as public: a model has to do the same.
        ForbiddenPublicPropertySniff::class => [
            'exclude' => ['src/Laravel/Models'],
        ],

        // Larastan writes the relations as BelongsTo<Commune, $this>, which this sniff does not understand.
        ReturnTypeHintSniff::class => [
            'exclude' => ['src/Laravel/Models'],
        ],
    ],
]);
