<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function down(): void
    {
        foreach (['commune_successions', 'cities', 'communes', 'departments', 'regions'] as $table) {
            Schema::connection($this->getConnection())->dropIfExists($this->table($table));
        }
    }

    public function getConnection(): ?string
    {
        $connection = config('french-postal-code.connection');

        return is_string($connection) && '' !== $connection ? $connection : null;
    }

    public function up(): void
    {
        $schema = Schema::connection($this->getConnection());

        // The identifiers come from the data and are never generated by the database.
        $schema->create($this->table('regions'), function (Blueprint $blueprint): void {
            $blueprint->unsignedBigInteger('id');
            $blueprint->string('code', 3);
            $blueprint->string('name');
            $blueprint->string('slug');
            $blueprint->date('valid_from');
            $blueprint->date('valid_to')->nullable();

            $blueprint->primary('id');

            $blueprint->unique(['code', 'valid_from']);
        });

        $schema->create($this->table('departments'), function (Blueprint $blueprint): void {
            $blueprint->unsignedBigInteger('id');
            $blueprint->unsignedBigInteger('region_id')->nullable();
            $blueprint->string('code', 3);
            $blueprint->string('type', 32);
            $blueprint->string('name');
            $blueprint->string('slug');
            $blueprint->date('valid_from');
            $blueprint->date('valid_to')->nullable();

            $blueprint->primary('id');

            $blueprint->unique(['code', 'valid_from']);
            $blueprint->foreign('region_id')->references('id')->on($this->table('regions'))->restrictOnDelete();
        });

        $schema->create($this->table('communes'), function (Blueprint $blueprint): void {
            $blueprint->unsignedBigInteger('id');
            $blueprint->unsignedBigInteger('department_id')->nullable();
            $blueprint->string('insee_code', 5);
            $blueprint->string('kind', 4);
            $blueprint->string('name');
            $blueprint->string('slug');
            $blueprint->double('centre_latitude')->nullable();
            $blueprint->double('centre_longitude')->nullable();
            $blueprint->date('valid_from');
            $blueprint->date('valid_to')->nullable();

            $blueprint->primary('id');

            $blueprint->unique(['insee_code', 'valid_from']);
            $blueprint->index('insee_code');
            $blueprint->foreign('department_id')->references('id')->on($this->table('departments'))->restrictOnDelete();
        });

        $schema->create($this->table('cities'), function (Blueprint $blueprint): void {
            $blueprint->unsignedBigInteger('id');
            $blueprint->unsignedBigInteger('commune_id');
            $blueprint->string('postal_code', 5);
            $blueprint->string('label')->nullable();
            $blueprint->double('latitude')->nullable();
            $blueprint->double('longitude')->nullable();
            $blueprint->unsignedInteger('address_count')->default(0);
            $blueprint->string('coordinate_source', 32)->nullable();
            $blueprint->date('valid_from');
            $blueprint->date('valid_to')->nullable();
            $blueprint->unsignedBigInteger('replaced_by_city_id')->nullable();

            // Declared before the foreign keys: PostgreSQL needs it to exist for a foreign key to the same table.
            $blueprint->primary('id');

            $blueprint->unique(['commune_id', 'postal_code', 'valid_from']);
            $blueprint->index('postal_code');
            $blueprint->foreign('commune_id')->references('id')->on($this->table('communes'))->restrictOnDelete();
            $blueprint->foreign('replaced_by_city_id')->references('id')->on($this->table('cities'))->restrictOnDelete();
        });

        $schema->create($this->table('commune_successions'), function (Blueprint $blueprint): void {
            $blueprint->unsignedBigInteger('id');
            $blueprint->string('from_code', 5);
            $blueprint->string('to_code', 5)->nullable();
            $blueprint->string('kind', 32);
            $blueprint->date('effective_date');

            $blueprint->primary('id');

            $blueprint->index(['from_code', 'effective_date']);
        });
    }

    private function table(string $name): string
    {
        $prefix = config('french-postal-code.table_prefix');

        return (is_string($prefix) ? $prefix : 'french_') . $name;
    }
};
